/* ==========================================================================
   gen-photos.mjs — regenerate the PHOTOS library in public/js/templates.js
   from whatever actually sits in public/mu/images + public/assets, so no
   layout can ever reference a photo id that has no file behind it.

   Run:  node .zscripts/gen-photos.mjs
   ========================================================================== */
import { readdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const MU = resolve(ROOT, 'public/mu/images');
const TPL = resolve(ROOT, 'public/js/templates.js');

/* Only the numbered photographs — the folders also hold decorative shapes,
   flowers and icons, which belong to the design rather than the picker.
   `image.jpg` counts as number 1, so an id maps straight onto the template's
   own filename: hero/image-4.jpg → mu-hero-4. */
const PHOTO_FILE = /^(?:image|img)(?:-(\d+))?\.(?:jpe?g|png)$/i;

/* Folders that hold usable photography, in the order they appear in the
   editor's picker, with the label shown next to each thumbnail. */
const GROUPS = [
  ['hero', 'Hero'],
  ['couple', 'Portrait'],
  ['story', 'Story'],
  ['gallery', 'Gallery'],
  ['portfolio', 'Photo'],
  ['event', 'Detail'],
  ['rsvp', 'RSVP panel'],
  ['blog', 'Card'],
  ['product', 'Gift'],
  ['quote', 'Quote'],
  ['wedding-date', 'Date frame'],
  ['offer-image', 'Feature']
];

/* Single files at the root of mu/images worth offering. */
const SINGLES = [
  ['video.jpg', 'mu-video', 'Video still'],
  ['video-2.jpg', 'mu-video-2', 'Video still 2'],
  ['cta.jpg', 'mu-cta', 'Invitation band'],
  ['contact-bg.jpg', 'mu-contact', 'Contact backdrop'],
  ['pricing/bg.jpg', 'mu-soft', 'Soft backdrop']
];

/* Returns [{file, n}] sorted numerically (image-3 before image-10). */
function safeList(dir) {
  let files;
  try { files = readdirSync(dir); } catch { return []; }
  return files
    .map((f) => {
      const m = f.match(PHOTO_FILE);
      return m ? { file: f, n: Number(m[1] || 1) } : null;
    })
    .filter(Boolean)
    .sort((a, b) => a.n - b.n);
}

const rows = [];
rows.push('    /* Muhibbi template photography — public/mu/images.');
rows.push('       GENERATED by .zscripts/gen-photos.mjs; re-run it after adding files. */');

for (const [folder, label] of GROUPS) {
  const files = safeList(join(MU, folder));
  if (!files.length) continue;
  const slug = folder === 'wedding-date' ? 'date' : folder === 'offer-image' ? 'offer' : folder;
  files.forEach(({ file, n }) => {
    rows.push(`    { id: 'mu-${slug}-${n}', src: 'mu/images/${folder}/${file}', label: '${label} ${n}' },`);
  });
}
for (const [file, id, label] of SINGLES) {
  try { statSync(join(MU, file)); } catch { continue; }
  rows.push(`    { id: '${id}', src: 'mu/images/${file}', label: '${label}' },`);
}

/* Ever RSVP's own occasion photography stays available for the non-wedding
   themes, where the template's imagery would read as a wedding. */
const OWN = [
  ['couple', 'ws-couple.jpg', 'Couple portrait'],
  ['cafe', 'ws-cafe.jpg', 'First meeting'],
  ['proposal', 'ws-proposal.jpg', 'The proposal'],
  ['rings', 'ws-rings.jpg', 'The rings'],
  ['dance', 'ws-dance.jpg', 'First dance'],
  ['decor', 'ws-decor.jpg', 'Reception decor'],
  ['shoes', 'hero.jpg', 'Bridal style'],
  ['band', 'cta-band.jpg', 'Celebration'],
  ['balloons', 'ev-balloons.jpg', 'Balloons & confetti'],
  ['neon', 'ev-neon.jpg', 'Neon party'],
  ['glam', 'ev-glam.jpg', 'Glam party table'],
  ['tropical', 'ev-tropical.jpg', 'Tropical pool party'],
  ['anniv', 'ev-anniv.jpg', 'Anniversary table'],
  ['silver', 'ev-silver.jpg', 'Silver celebration'],
  ['home', 'ev-home.jpg', 'New home porch'],
  ['cottage', 'ev-cottage.jpg', 'Cottage garden'],
  ['baptism', 'ev-baptism.jpg', 'Christening candles'],
  ['baby', 'ev-baby.jpg', 'Baby shower'],
  ['gala', 'ev-gala.jpg', 'Gala ballroom'],
  ['star', 'ev-star.jpg', 'Star party']
];
rows.push('    /* Ever RSVP occasion photography — public/assets. */');
OWN.forEach(([id, file, label], i) => {
  const last = i === OWN.length - 1;
  rows.push(`    { id: '${id}', src: 'assets/${file}', label: '${label}' }${last ? '' : ','}`);
});

const block = '  var PHOTOS = [\n' + rows.join('\n') + '\n  ];\n';

const src = readFileSync(TPL, 'utf8');
const start = src.indexOf('  var PHOTOS = [');
const end = src.indexOf('\n  ];\n', start) + '\n  ];\n'.length;
if (start < 0 || end < start) throw new Error('PHOTOS block not found in templates.js');
writeFileSync(TPL, src.slice(0, start) + block + src.slice(end));

const count = rows.filter((r) => r.includes("{ id:")).length;
console.log('wrote PHOTOS with', count, 'entries');
